# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x6DXzhuNO2ekpQVZmNY2pmyKbeFRVfiZ
"""

import numpy as np
import pandas as pd

from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

im = Image.open('YM.SU3.60.tiff')

im.show()

img2=im.crop((70,90,184,230))

imarray = np.array(img2)

imarray.shape

imarray

imgplot = plt.imshow(im)
plt.show()

imgplot = plt.imshow(img2)
plt.show()

N=11

def mean(i,j):
  a=int((N-1)/2)
  u=0
  for k in range(-a,a):
    for h in range(-a,a):
      u=u+imarray[k+i][h+j]
#   print(u)
  u=np.float128(u/(N*N))
  return u

def st_dev(i,j):
  a=int((N-1)/2)
  sd=0
  for k in range(-a,a):
    for h in range(-a,a):
      m=mean(i,j)
      sd=sd+np.square(imarray[k+i][h+j]-m)
  sd=np.float128(sd/(N*N))
  sd=np.sqrt(sd)
  return sd

def normalize(i,j):
  print("i",i)
  print("j",j)
  m=mean(i,j)
  print("mean",m)
  sd=st_dev(i,j)
  print("sd",sd)
  imarray[i][j]=np.float128((imarray[i][j]-m)/(6*sd))

for i in range(0,50):
  for j in range(0,50):
    normalize(i,j)

img3 = Image.fromarray(imarray)
imgplot = plt.imshow(img3)
plt.show()